myapp/blueprints/questionare.py
from http import HTTPStatus
from webargs import fields
from flask_login import current_user, login_required
from myapp.model.db_extension import db
from webargs.flaskparser import use_args
from flask import request, redirect, url_for
from flask import Blueprint, jsonify, render_template
from myapp.bl.QuestionnaireBLC import QuestionnaireBLC
from myapp.repositories.QuestionareRepository import QuestionareRepository


questionare = Blueprint("questionare", __name__)


@questionare.route("/get_form_data", methods=["GET"])
# @login_required
def get_form_data():
    data = QuestionareRepository.get_questions_data()
    schema = QuestionareRepository.get_schema(many=True)
    mixed_result = schema.dump(data)
    result = QuestionnaireBLC.data_serialization(mixed_result)

    return jsonify(result), HTTPStatus.OK


@questionare.route("/get_form_list", methods=["GET"])
@login_required
def get_submissions_data():
    if current_user.id != 4:
        user_id = current_user.id
    else:
        user_id = None
    data = QuestionareRepository.get_form_list(user_id=user_id)
    schema = QuestionareRepository.get_form_schema(many=True)
    result = schema.dump(data)
    return jsonify(result), HTTPStatus.OK


def get_data_by_user_form_id(meta_form_id):
    data = QuestionareRepository.get_response_data(meta_form_id)
    if not data:
        return jsonify([]), HTTPStatus.NO_CONTENT
    schema = QuestionareRepository.get_response_schema(many=True)
    mixed_result = schema.dump(data)

    return mixed_result


@questionare.route("/post_data", methods=["POST", "GET"])
@login_required
def post_form_data():
    total_questions_len = QuestionareRepository.get_questions_count()
    submissions_count = QuestionnaireBLC.submissions_count(request.form)

    if submissions_count != total_questions_len:
        return redirect(request.referrer)
    incoming_args = request.form
    try:
        qna_dict, desc_dict, meta_system = QuestionnaireBLC.get_required_param(
            incoming_args,
        )
    except Exception as _:
        return redirect(request.referrer)
        print(_)

    response_data = {
        "qna_dict": qna_dict,
        "description_list": desc_dict,
        "meta_system": meta_system,
    }
    response_list = QuestionnaireBLC.data_serializer(data=response_data)
    _ = QuestionareRepository.add_responses(response_list)
    db.session.commit()
    return redirect(url_for("main.home_page"))


@questionare.route("/show_form/", methods=["GET", "POST"])
@login_required
def get_questionnaire_form():
    result = get_form_data()
    systems = QuestionareRepository.get_systems()
    years_list = QuestionnaireBLC.get_years()
    return render_template(
        "meta_data_form.html",
        all_categories=result[0].json,
        all_systems=systems,
        years_list=years_list,
        systems_list=systems,
    )


@questionare.route("/show_history/", methods=["GET", "POST"])
@login_required
def get_history():
    result = get_submissions_data()
    headers_list = ["FORM", "Created On", "Updated On", "Action"]
    return render_template(
        "data_history.html",
        all_submissions=result[0].json,
        all_headers=headers_list,
    )


@questionare.route("/deleteform", methods=["GET"])
@login_required
def delete_post():
    form_id = request.args.get("meta_form_id")
    target_form = QuestionareRepository.get_forms(form_id=form_id)
    if target_form:
        QuestionareRepository.delete_responses_by_id(form_id=form_id)
        QuestionareRepository.delete_form(target_form)
        db.session.commit()
        return redirect(url_for("questionare.get_history"))
    else:
        return redirect(url_for("questionare.get_history"))


@questionare.route("/edit_form/", methods=["GET"])
@login_required
def edit_questionnaire_form():
    result = get_form_data()
    result = result[0].json

    form_id = request.args.get("meta_form_id")
    responses_list = get_data_by_user_form_id(form_id)
    response_data = QuestionnaireBLC.responses_obj_generator(responses_list)
    data = QuestionnaireBLC.merge_answers_in_questions(result, response_data)
    target_form = QuestionareRepository.get_forms(form_id=form_id)
    systems = QuestionareRepository.get_systems()
    years_list = QuestionnaireBLC.get_years()
    target_system_id = target_form.meta_system_id
    return render_template(
        "meta_data_edit_form.html",
        all_categories=data,
        form_id=form_id,
        all_systems=systems,
        years_list=years_list,
        systems_list=systems,
        target_system=target_system_id,
    )


@questionare.route("/edit_data", methods=["POST", "GET"])
@login_required
@use_args({"form_id": fields.Integer(required=True)}, location="query")
def edit_form_data(args: dict):
    form_id = args["form_id"]
    incoming_args = request.form
    breakpoint()
    try:
        ques_list, ans_list, desc_dict = QuestionnaireBLC.get_required_param(
            incoming_args,
        )
    except Exception as _:
        return redirect(request.referrer)
        print(_)

    response_data = {
        "questions_list": ques_list,
        "answers_list": ans_list,
        "description_list": desc_dict,
    }
    QuestionareRepository.delete_responses_by_id(form_id=form_id)
    response_list = QuestionnaireBLC.data_serializer(
        data=response_data,
        form_id=form_id,
        session=db.session,
    )
    _ = QuestionareRepository.add_responses(response_list)
    db.session.commit()
    return redirect(url_for("questionare.get_history"))

myapp/views/home.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

main = Blueprint("main", __name__)


@main.route("/")
def home_page():
    return render_template("index.html")


@main.route("/profile")
@login_required
def get_profile():
    return render_template("profile.html", username=current_user.username)

myapp/views/posts.py
from datetime import datetime
from myapp.model.db_extension import db
from myapp.model.post_model import Posts, PostsSchema
from flask import Blueprint, render_template, request, url_for, flash, redirect
from flask_login import login_required, current_user

posts = Blueprint("posts", __name__, url_prefix="/api")


@posts.route("/getposts", methods=["GET", "POST"])
@login_required
def get_posts():
    all_posts = Posts.query.filter_by(user_id=current_user.id)
    if all_posts:
        user_posts = all_posts.all()
        post_schema = PostsSchema(many=True)
        output = post_schema.dump(user_posts)
        return render_template("posts.html", all_posts=output)

        # return jsonify(output)
    else:
        return render_template("posts.html", all_posts=[])


@posts.route("/createpost", methods=["GET"])
@login_required
def create_post_get():
    return redirect(url_for("questionare.get_questionnaire_form"))


@posts.route("/createpost", methods=["POST"])
@login_required
def create_post():
    post_title = request.form.get("title")
    post_description = request.form.get("description")
    created_at = datetime.now()
    user_id = current_user.id

    # Incodicates Post already exists in database
    prev_post = Posts.query.filter_by(title=post_title).first()

    # Redirect to Create_Post Page if Post already exists
    if prev_post:
        flash("A Post with Same Title Already Exists in Database")
        return redirect(url_for("posts.create_post"))

    new_post = Posts(
        title=post_title,
        description=post_description,
        created_at=created_at,
        user_id=user_id,
    )

    db.session.add(new_post)
    db.session.commit()

    return redirect(url_for("posts.get_posts"))


@login_required
@posts.route("/updatepost", methods=["PUT", "POST"])
def update_post():
    # post_id = request.form.get("id")
    # target_post_data = Posts.query.get_or_404(post_id)
    # if target_post_data:
    #     post_title = target_post_data.get("title")
    #     post_description = target_post_data.get("description")
    #     created_at = target_post_data.get("created_at")
    #     user_id = current_user.id
    #     updated_at = datetime.now()

    pass


@login_required
@posts.route("/deletepost", methods=["GET"])
def delete_post():
    post_id = request.args.get("id")
    breakpoint()
    target_post = Posts.query.get_or_404(post_id)
    if target_post:
        db.session.delete(target_post)
        db.session.commit()
        return redirect(url_for("posts.get_posts"))
    else:
        return redirect(url_for("posts.get_posts"))

myapp/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Metadata Gathering Application</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;700;900&display=swap"
        rel="stylesheet">
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <link href="../static/css/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/css/magnific-popup.css">
    <link href="../static/css/aos.css" rel="stylesheet">
    <link href="../static/css/templatemo-nomad-force.css" rel="stylesheet">
    <style>
        form {
            width: 98%;
            padding: 20px;
            border-radius: 6px;
            background: #eee;
            line-height: 25px;
            display: grid;
        }

        .contact-form button[type='submit'] {
            background: var(--dark-color);
            border: none;
            border-radius: 100px;
            color: var(--white-color);
            font-weight: var(--font-weight-bold);
            text-transform: uppercase;
            padding: 16px;
            transition: all 0.6s ease-out;
        }

        .button-form {
            background: var(--dark-color);

            border: none;
            border-radius: 100px;
            color: var(--white-color);
            font-weight: var(--font-weight-bold);
            text-transform: uppercase;
            padding: 16px;
            transition: all 0.6s ease-out;
            width: 170px;
            height: 65px;
        }


        .button-form:hover {
            background: #fff;
            color: #000;
            border: 3px solid black;
            border-radius: 100px;
            font-weight: var(--font-weight-bold);
            text-transform: uppercase;
            padding: 16px;
            transition: all 0.6s ease-out;
            width: 170px;
            height: 65px;
        }
    </style>
    <script type="text/javascript">
        function ShowHideDiv(chkPassport) {
            var dvPassport = document.getElementById(chkPassport);
            dvPassport.style.display = "block";
        }
    </script>
</head>

<body>

    <main>

        <section class="hero" id="hero">
            <div class="heroText">
                <h1 class="text-white mt-5 mb-lg-4" data-aos="zoom-in" data-aos-delay="800">
                    Metadata Gathering Application
                </h1>

                <p class="text-secondary-white-color" data-aos="fade-up" data-aos-delay="1000">
                    Let us have your <strong class="custom-underline">Data!!</strong>
                </p>
            </div>

            <div class="videoWrapper">

                <img src="../static/images/Banner.jpg" />
            </div>

            <div class="overlay"></div>
        </section>

        <nav class="navbar navbar-expand-lg bg-light shadow-lg">
            <div class="container">
                <a class="navbar-brand" href="index.html">
                    <strong>MGA System</strong>
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ url_for('main.home_page') }}">Home</a>
                        </li>

                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('questionare.get_history') }}">Data History</a>
                        </li>
                        {% endif %}
                        <!-- 
                            <li class="nav-item">
                                <a class="nav-link" href="#news">User Management</a>
                            </li>
                        -->

                        {% if not current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        {% endif %}

                        {% if current_user.is_authenticated and current_user.id==4 %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign Up</a>
                        </li>
                        {% endif %}

                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div>
            {% block content %}
            {% endblock %}
        </div>

    </main>

    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <p class="copyright-text mb-0">
                        Copyright © DC 2022
                    </p>
                </div>
            </div>
            </section>
    </footer>

    <!-- JAVASCRIPT FILES -->
    <script src="../static/js/jquery.min.js"></script>
    <script src="../static/js/bootstrap.bundle.min.js"></script>
    <script src="../static/js/jquery.sticky.js"></script>
    <script src="../static/js/aos.js"></script>
    <script src="../static/js/jquery.magnific-popup.min.js"></script>
    <script src="../static/js/magnific-popup-options.js"></script>
    <script src="../static/js/scrollspy.min.js"></script>
    <script src="../static/js/custom.js"></script>

</body>

</html>

myapp/templates/data_history.html
{% extends "base.html" %}

{% block content %}

{% if current_user.is_authenticated %}
<h1 class="title">
    <strong>&nbsp; Welcome To Your History </strong>
</h1>
{% endif %}

{% if not current_user.is_authenticated %}
<h1 class="title">
    <strong> Please Login to View your History </strong>
</h1>
{% endif %}


<head>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
            margin-left: 2%;
            margin-top: 2%;
            margin-bottom: 2%;

        }

        td,
        th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        td>a:link,
        a:visited {
            background-color: #000;
            color: white;
            padding: 14px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            border-radius: 25px;
            width: 120px;
            height: 50px;
        }

        td>a:hover,
        a:active {
            background-color: white;
            color: black;
            border: 3px solid black;
        }
    </style>
</head>

<body>


    {% if current_user.is_authenticated %}
    <table style="width:40%" id="data">

        {% if all_submissions %}
        <button class="button-form" style="width: 198px;margin-left: 2%;">
            <a href="{{ url_for('questionare.get_questionnaire_form') }}">Add New Response</a>
        </button>

        <tr>
            {% for single_header in all_headers %}
            {% if "Action" not in single_header %}
            <th>{{single_header}}</th>
            {% else %}
            <th colspan="2" style="text-align: center;">{{single_header}}</th>
            {% endif %}
            {% endfor %}
        </tr>

        {% for single_submission in all_submissions %}
        <tr>
            <td>
                {{loop.index}}
            </td>

            <td>
                {{single_submission.created_at}}
            </td>

            <td>
                {{single_submission.last_updated}}
            </td>


            <td>
                <form action="{{ url_for('questionare.edit_questionnaire_form') }}" method=GET>
                    <input type=hidden value="{{ single_submission.meta_form_id }}" name=meta_form_id />
                    <input class="button-form" type=submit value="Update" />
                </form>
            </td>

            <td>
                <form action="{{ url_for('questionare.delete_post') }}" method=GET>
                    <input type=hidden value="{{ single_submission.meta_form_id }}" name=meta_form_id />
                    <input class="button-form" type=submit value="Delete" />
                </form>
            </td>



        </tr>
        {% endfor %}

        {% else %}
        <h2>
            <div>
                No Submissions Found
            </div>
            <button>
                <a href="{{ url_for('questionare.get_questionnaire_form') }}">Create New Post</a>
            </button>
        </h2>

        {% endif %}

    </table>

</body>
{% endif %}

{% endblock %}

myapp/templates/data_history_bkp.html
{% extends "base.html" %}

{% block content %}

{% if current_user.is_authenticated %}
<h1 class="title">
    <strong> Welcome To Your History </strong>
</h1>
{% endif %}

{% if not current_user.is_authenticated %}
<h1 class="title">
    <strong> Please Login to View your History </strong>
</h1>
{% endif %}

{% if current_user.is_authenticated %}
<table id="data" class="table table-striped" , align="center">
    {% if all_submissions %}
    <button class="button-form">
        <a href="{{ url_for('questionare.get_questionnaire_form') }}">Add New Response</a>
    </button>
    <thead>
        <th>
            <strong>Form</strong>
        </th>

        <th>
            <strong>Submitted On</strong>
        </th>

        <th>
            <strong>Last Updated</strong>
        </th>

    </thead>

    <tbody>

        {% for single_submission in all_submissions %}
        <tr>
            <td>
                {{loop.index}}
            </td>

            <td>
                {{single_submission.created_at}}
            </td>

            <td>
                {{single_submission.last_updated}}
            </td>


            <td>
                <form action="{{ url_for('posts.delete_post') }}" method=GET class="button-form">
                    <input type=hidden value="{{ single_submission.meta_form_id }}" name=meta_form_id />
                    <input type=submit value="Delete" />

                </form>
            </td>

        </tr>
        {% endfor %}

    </tbody>

    {% else %}
    <h2>
        <div>
            No Posts Found
        </div>
        <button>
            <a href="{{ url_for('questionare.get_questionnaire_form') }}">Create New Post</a>
        </button>
    </h2>

    {% endif %}

    {% endif %}
</table>



{% endblock %}

myapp/templates/index.html
{% extends "base.html" %}

{% block content %}
<center>
    <h2 class="mb-3 aos-init aos-animate" data-aos="fade-up">Welcome To Metadata Gathering Application...</h2>

    {% if current_user.is_authenticated %}
    <p class="me-4 aos-init aos-animate" data-aos="fade-up" data-aos-delay="300">Logged in Successfully...
    </p>
    {% endif %}

    {% if not current_user.is_authenticated %}
    <p class="me-4 aos-init aos-animate" data-aos="fade-up" data-aos-delay="300">You are Not Logged In --- Please
        <a rel="nofollow" href="{{ url_for('auth.login') }}" target="_blank"><strong>Login</strong></a>
        to Submit and View your Data
    </p>
    {% endif %}
</center>


{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}

{% block content %}
<section class=" contact section-padding" id="contact">
    <div class="container">
        <div class="row">

            <div class="col-lg-7 col-12 mx-auto">

                <h2 class="mb-4 text-center" data-aos="fade-up">Provide your Credentials</h2>

                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
                {% endif %}
                {% endwith %}
                <form action="#" method="post" class="contact-form" role="form" data-aos="fade-up">
                    <div class="row">
                        <div class="col-lg-3 col-6">

                        </div>
                        <div class="col-lg-6 col-6">
                            <label for="name" class="form-label">USERNAME <sup class="text-danger">*</sup></label>

                            <input type="text" name="username" id="username" class="form-control" placeholder="Username"
                                required>
                        </div>

                        <div class="col-lg-3 col-6">

                        </div>
                        <div class="col-lg-3 col-6">

                        </div>
                        <div class="col-lg-6 col-6" style="margin-top: 1%;">
                            <label for="email" class="form-label">PASSWORD <sup class="text-danger">*</sup></label>

                            <input type="password" name="password" id="password" class="form-control"
                                placeholder="Password" required>
                        </div>
                        <div class="col-lg-3 col-6">

                        </div>

                        <div class="col-12">
                        </div>
                        <div class="col-lg-3 col-6">

                        </div>
                        <div class="col-lg-6 col-12" style="margin-top: 1%;">
                            <div class="form-check">
                                <input type="checkbox" id="checkbox" name="checkbox" class="form-check-input">

                                <label class="form-check-label" for="remember">Remember Me</label>
                            </div>
                        </div>
                        <div class="col-lg-3 col-6">

                        </div>

                    </div>

                    <div class="col-lg-5 col-12 mx-auto mt-5">
                        <button type="submit" class="form-control">Login</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</section>
{% endblock %}

myapp/templates/meta_data_edit_form.html
{% extends "base.html" %}

{% block content %}

<head>
    <title>Metadata Gathering Form</title>
    <link href="../static/css/main.css" rel="stylesheet">
</head>

<body>
    <div class="testbox" style="margin-left:1%;margin-bottom:1%">
        <form method="post" action="/edit_data?form_id={{form_id}}">
            <h2>
                Select System
            </h2>
            <br>
            <select id="system" name="system">
                <option value="Select System" required>
                    Select System</option>
                {% for single_system in systems_list %}
                {% if single_system.meta_system_id == target_system %}
                <option value="{{single_system.meta_system_id}}" selected>{{single_system.system_name}}</option>
                {% else %}
                <option value="{{single_system.meta_system_id}}">{{single_system.system_name}}</option>
                {% endif %}
                {% endfor %}

            </select>
            <br>
            <br>
            <br>

            {% if all_categories %}
            {% if all_systems %}

            {% for single_category in all_categories %}
            <label>
                <h2>{{single_category.category}}</h2>
                <br>

                {% for single_question in single_category.questions %}
                <div class="question" id="ques{{single_question.meta_question_id}}">
                    <label>
                        <strong>{{single_question.meta_question_id}}.
                            {{single_question.meta_question}}
                        </strong>
                    </label>

                    <div class="question-answer">
                        <br>
                        {% set flag="True" %}
                        {% for single_choice in single_question.choices %}
                        <div>

                            {% if single_question.meta_question_id == 3 %}
                            <select id="desc_{{single_question.meta_question_id}}"
                                name="desc_{{single_question.meta_question_id}}">
                                <option value="{{single_question.desc[single_choice.meta_choices_id]}}" selected
                                    required>
                                    {{single_question.desc[single_choice.meta_choices_id]}}</option>
                                {% for single_year in years_list %}
                                <option value="{{single_year}}">{{single_year}}</option>
                                {% endfor %}

                            </select>

                            <input type="hidden" value="{{single_choice.meta_choices_id}}"
                                id="choice{{single_choice.meta_choices_id}}"
                                name="ques_{{single_question.meta_question_id}}" checked />


                            {% else %}
                            {% if flag=="True" and single_choice.meta_choices_id in single_question.selection %}
                            <label class="checkbox_container">{{single_choice.meta_choice_desc}}
                                <input type="checkbox" value="{{single_choice.meta_choices_id}}"
                                    id="choice{{single_choice.meta_choices_id}}"
                                    name="ques_{{single_question.meta_question_id}}"
                                    onchange="ShowHideDiv('desc_{{single_choice.meta_choices_id}}')" required checked />
                                {% set flag="False" %}
                                <span class="checkmark"></span>
                            </label>

                            {% elif flag=="False" and single_choice.meta_choices_id in single_question.selection %}
                            <label class="checkbox_container">{{single_choice.meta_choice_desc}}
                                <input type="checkbox" value="{{single_choice.meta_choices_id}}"
                                    id="choice{{single_choice.meta_choices_id}}"
                                    name="ques_{{single_question.meta_question_id}}"
                                    onchange="ShowHideDiv('desc_{{single_choice.meta_choices_id}}')" checked />
                                {% set flag="False" %}
                                <span class="checkmark"></span>
                            </label>

                            {% else %}
                            <label class="checkbox_container">{{single_choice.meta_choice_desc}}
                                <input type="checkbox" value="{{single_choice.meta_choices_id}}"
                                    id="choice{{single_choice.meta_choices_id}}"
                                    name="ques_{{single_question.meta_question_id}}"
                                    onchange="ShowHideDiv('desc_{{single_choice.meta_choices_id}}')" />
                                {% set flag="False" %}
                                <span class="checkmark"></span>
                            </label>
                            {% endif %}

                            {% if "Please Specify" in single_choice.meta_choice_desc %}
                            {% if single_choice.meta_choices_id in single_question.desc.keys() %}
                            <input id="desc_{{single_choice.meta_choices_id}}"
                                name="desc_{{single_question.meta_question_id}}_{{single_choice.meta_choices_id}}"
                                type="text" style="display: none" class="form-control"
                                value='{{single_question.desc[single_choice.meta_choices_id]}}' />

                            {% else %}
                            <input id="desc_{{single_choice.meta_choices_id}}"
                                name="desc_{{single_question.meta_question_id}}_{{single_choice.meta_choices_id}}"
                                type="text" style="display: none" class="form-control" value='' />
                            {% endif %}
                            {% endif %}
                            {% endif %}

                        </div>
                        {% endfor %}

                    </div>

                    <br>
                    <br>

                </div>
                {% endfor %}
            </label>
            {% endfor %}

            {% endif %}
            {% endif %}

            <center>
                <div>
                    <button class="button-form" type="button" href="/show_history">Cancel</button>
                    <button class="button-form" type="submit" href="/show_history">Submit</button>
                </div>
            </center>

        </form>
    </div>
</body>
{% endblock %}

myapp/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, to Your Profile {{username}}!
</h1>
{% endblock %}

myapp/templates/signup.html
{% extends "base.html" %}

{% if current_user.id == 4 %}
{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
        </div>
        {% endif %}
        {% endwith %}

        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" placeholder="User Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}
{% endif %}